#!/bin/bash

###############
#   HEADER
###############

# Version
echo '{"version":1}'

# Start the content array
echo '[[]'

# Prepare i3 json buffer
I3LB_BUFFER=""

#################
#    CONFIG
#################

# Refresh time (second)
I3LB_SLEEP=5

#################
#  JSON ENTRY
#################

# Template for the i3bar json entry
function i3_json_entry() {
    # Params
    local l_name="$1"
    local l_full_text="$2"

    # Template json entry
    I3LB_BUFFER="${I3LB_BUFFER},{\"name\":\"${l_name}\",\"full_text\":\"${l_full_text}\"}"
}

# Prepare the json header
function i3_json_header() {
    I3LB_BUFFER=",[{\"full_text\":\"\"}"
}

# Prepare the json footer
function i3_json_footer() {
    I3LB_BUFFER="${I3LB_BUFFER}]"
}

###############
#    TABS
###############

# Show date
function i3lb_date() {
    i3_json_entry "time" "$(date "+$1")"
}

# Battery info
function i3lb_simple_battery() {
    local capacity=$(cat /sys/class/power_supply/BAT${1}/capacity)
    local status=$(cat /sys/class/power_supply/BAT${1}/status)
    i3_json_entry "simple_battery" "${capacity}% ${status}"
}

# System volume
function i3lb_simple_volume() {
    local vol=$(pactl list sinks | command grep "Volume: front" | awk '{print $5}')
    local mute=$(pactl list sinks | command grep "Mute:" | awk '{print $2}')
    if [[ $mute == "yes" ]]; then
        vol="0%"
    fi
    i3_json_entry "volume" "Volume ${vol}"
}

###############
#    SIGNAL
###############
function i3_USR1_handler() {

    # Refresh on USR1 signal
    i3_call
}

###############
#     MAIN
###############

# Tabs in order
function i3_refresh() {
    i3lb_date "%Y-%m-%d %a %H:%M"
    i3lb_simple_battery 0
    i3lb_simple_volume
}

# Steps required for generating JSON
function i3_call() {
    I3LB_BUFFER=""
    i3_json_header
    i3_refresh
    i3_json_footer
    echo ${I3LB_BUFFER}
}

# Main function
function i3_main() {
    # Register handler for USR1
    trap "i3_USR1_handler" SIGUSR1

    # Now send blocks with information forever:
    while :;
    do
        i3_call
        sleep ${I3LB_SLEEP} &
        wait
    done
}

# Call main function
i3_main
